stages:
- package

variables:
  DOCKER_HOST: tcp://172.24.67.199:2375

Package - consumer image:
  image: $CI_REGISTRY/build/docker:stable
  stage: package
  only: 
    - master
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build --no-cache -t $CI_REGISTRY_IMAGE/consumer:latest -f ./Dockerfile . 
  - docker push $CI_REGISTRY_IMAGE/consumer:latest
  when: manual

Package Dev - Consumer image:
  image: $CI_REGISTRY/build/docker:stable
  stage: package
  except: 
    - master
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build --no-cache -t $CI_REGISTRY_IMAGE/consumer:latest -f ./Dockerfile . 
  - docker push $CI_REGISTRY_IMAGE/consumer:latest
  when: manual