apiVersion: apps/v1
kind: Deployment
metadata:
  name: igbi-kafka-connect-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igbi-kafka-connect-host
  template:
    metadata:
      labels:
        app: igbi-kafka-connect-host
    spec:
      containers:
      - name: igbi-kafka-connect-host
        image: artifactory.tools1-az1.digi.is/epea-docker-local/kafka-connect-base-build:latest
        #image: artifactory.tools1-az1.digi.is/epea-docker-local/ep-kafka-connect:latest
        #image: registry.digi.is/bi-platform-apps/kafka-connect-base-build/master/cp-kafka-connect-base:latest
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            memory: 4Gi
            cpu: 2000m
        env:
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: $BOOTSTRAP_SERVERS
        - name: CONNECT_REST_PORT
          value: "8083"
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: $ADVERTISED_HOST_NAME           
        - name: CONNECT_GROUP_ID
          value: "EVT_IGBI_DEV_KC_$CONNECTOR_NAME"
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: "$CONNECTOR_NAME_OFFSETS_CONFIGS"
          #value: "EVT_DOSCPT_IGBI_DEV_KC_configs_$CONNECTOR_NAME"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: "$CONNECTOR_NAME_OFFSETS"
          #value: "EVT_DOSCPT_IGBI_DEV_KC_offsets_$CONNECTOR_NAME"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: "$CONNECTOR_NAME_OFFSETS_STATUS"
          #value: "EVT_DOSCPT_IGBI_DEV_KC_status_$CONNECTOR_NAME"
        - name: CONNECT_REPLICATION_FACTOR
          value: "3"
        - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
          value: "3"
        - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
          value: "3"
        - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
          value: "3"
        - name: CONNECT_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_INTERNAL_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_INTERNAL_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        # Connect worker
        - name: CONNECT_SECURITY_PROTOCOL
          value: SASL_SSL
        - name: CONNECT_SASL_MECHANISM
          value: "SCRAM-SHA-256"
        - name: CONNECT_SASL_JAAS_CONFIG
          value: "org.apache.kafka.common.security.scram.ScramLoginModule required username='$DEV_KAFKA_USERNAME' password='$DEV_KAFKA_PASSWORD';"
        - name: CONNECT_SSL_TRUSTSTORE_LOCATION
          value: "/usr/local/share/ca-certificates/fsca.pem"
        - name: CONNECT_SSL_TRUSTSTORE_TYPE
          value: PEM
        # Connect Producer
        - name: CONNECT_PRODUCER_SECURITY_PROTOCOL
          value: SASL_SSL
        - name: CONNECT_PRODUCER_SASL_MECHANISM
          value: "SCRAM-SHA-256"
        - name: CONNECT_PRODUCER_SASL_JAAS_CONFIG
          value: "org.apache.kafka.common.security.scram.ScramLoginModule required username='$DEV_KAFKA_USERNAME' password='$DEV_KAFKA_PASSWORD';"
        - name: CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION
          value: "/usr/local/share/ca-certificates/fsca.pem"
        - name: CONNECT_PRODUCER_SSL_TRUSTSTORE_TYPE
          value: PEM
        # Connect Consumer
        - name: CONNECT_CONSUMER_SECURITY_PROTOCOL
          value: SASL_SSL
        - name: CONNECT_CONSUMER_SASL_MECHANISM
          value: "SCRAM-SHA-256"
        - name: CONNECT_CONSUMER_SASL_JAAS_CONFIG
          value: "org.apache.kafka.common.security.scram.ScramLoginModule required username='$DEV_KAFKA_USERNAME' password='$DEV_KAFKA_PASSWORD';"
        - name: CONNECT_CONSUMER_SSL_TRUSTSTORE_LOCATION
          value: "/usr/local/share/ca-certificates/fsca.pem"
        - name: CONNECT_CONSUMER_SSL_TRUSTSTORE_TYPE
          value: PEM
        - name: CONNECT_CONSUMER_GROUP_ID
          value: "EVT_IGBI_DEV_KC_CONSUMER_$CONNECTOR_NAME"        
        # Log4J
        - name: CONNECT_LOG4J_LOGGERS
          value: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
        - name: CONNECT_LOG4J_ROOT_LOGLEVEL
          value: INFO
        - name: CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN
          value: "[%d] %p %X{connector.context}%m (%c:%L)%n"
        # jmx exporter
        #- name: KAFKA_OPTS
        #  value: "-javaagent:/opt/kafka/libs/jmx_prometheus_javaagent.jar=7072:/opt/kafka/config/jmx_exporter_config.yml"
        #- name: KAFKA_JMX_OPTS
        #  value: "-javaagent:/usr/share/java/cp-base-new/jmx_prometheus_javaagent-0.19.0.jar=8080:/opt/kafka/config/jmx_exporter_config.yml -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
        ports:
        - name: http
          containerPort: 8080
...
apiVersion: v1
kind: Service
metadata:
  name: igbi-kafka-connect-host
  labels:
    app: igbi-kafka-connect-host
spec:
  type: NodePort
  selector:
    app: igbi-kafka-connect-host
  ports: 
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080