apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus-operator
  name: igbi-kafka-connect-host
spec:
  endpoints:
  - interval: 30s
    port: http
  selector:
    matchLabels:
      app: igbi-kafka-connect-host
