---
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: igp-kafka-connect 
data: 
   analysis01.password : "1g1K@fK@u53r!@#"
   analysis01.user : "svc_IGIKafkaUser"
   cptbidev02.password : "1g1K@fK@u53r!@#"
   cptbidev02.user : "svc_IGIKafkaUser"
   cptdevdb08.password : ""
   cptdevdb08.user : "svc_IGIKafkaUser"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: igp-kafka-connect 
  name: database-secrets-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [database-secrets]
    verbs: ["get"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: database-secrets-role-binding
  namespace: igp-kafka-connect 
subjects:
  - kind: ServiceAccount
    name: default 
    namespace: igp-kafka-connect 
roleRef:
  kind: Role
  name: database-secrets-reader
  apiGroup: rbac.authorization.k8s.io