/***********************************************************************************************************************************
* Script      : 99.Lookup -  Setup - CountryState.sql                                                                              *
* Created By  : Cedric Dube                                                                                                      *
* Created On  : 2021-09-06                                                                                                         *
* Execute On  : As required.                                                                                                       *
* Execute As  : N/A                                                                                                                *
* Execution   : Entire script.                                                                                                     *
* Version     : 1.0                                                                                                                *
* Notes       : DataSource: https://www.cbp.gov/document/guidance/international-stateprovince-codes                                *
***********************************************************************************************************************************/
USE [dbSurge]
GO
IF OBJECT_ID('TempDB..#CountryState') IS NOT NULL
  DROP TABLE #CountryState;
CREATE TABLE #CountryState (
  [CountryCode]      [CHAR](2) NOT NULL,
  [StateCode]    VARCHAR(3)  NOT NULL,
  [StateName] [NVARCHAR](256) NOT NULL
);

INSERT INTO #CountryState ([CountryCode], [StateCode], [StateName])
VALUES (	'--','---',N'Unknown'),
(	'AR','00',N'Capital Federal'),
(	'AR','01',N'Buenos Aires'),
(	'AR','02',N'Catamarca'),
(	'AR','03',N'Córdoba'),
(	'AR','04',N'Corrientes'),
(	'AR','05',N'Entre Rios'),
(	'AR','06',N'Jujuy'),
(	'AR','07',N'Mendoza'),
(	'AR','08',N'La Rioja'),
(	'AR','09',N'Salta'),
(	'AR','10',N'San Juan'),
(	'AR','11',N'San Luis'),
(	'AR','12',N'Santa Fé'),
(	'AR','13',N'Santiago del Estero'),
(	'AR','14',N'Tucumán'),
(	'AR','16',N'Chaco'),
(	'AR','17',N'Chubut'),
(	'AR','18',N'Formosa'),
(	'AR','19',N'Misiones'),
(	'AR','20',N'Neuquen'),
(	'AR','21',N'La Pampa'),
(	'AR','22',N'Rio Negro'),
(	'AR','23',N'Santa Cruz'),
(	'AR','24',N'Tierra de Fuego'),
(	'AT','B',N'Burgenland'),
(	'AT','K',N'Carinthia'),
(	'AT','NÖ',N'Lower Austria'),
(	'AT','OÖ',N'Upper Austria'),
(	'AT','S',N'Salzburg'),
(	'AT','ST',N'Styria'),
(	'AT','T',N'Tyrol'),
(	'AT','V',N'Vorarlberg'),
(	'AT','W',N'Vienna'),
(	'AU','ACT',N'Aust Capital Terr'),
(	'AU','NSW',N'New South Wales'),
(	'AU','NT',N'Northern Territory'),
(	'AU','QLD',N'Queensland'),
(	'AU','SA',N'South Australia'),
(	'AU','TAS',N'Tasmania'),
(	'AU','VIC',N'Victoria'),
(	'AU','WA',N'Western Australia'),
(	'BE','01',N'Antwerp'),
(	'BE','02',N'Brabant (Flemish),'),
(	'BE','03',N'Hainaut'),
(	'BE','04',N'Liege'),
(	'BE','05',N'Limburg'),
(	'BE','06',N'Luxembourg'),
(	'BE','07',N'Namur'),
(	'BE','08',N'Oost-Vlaanderen'),
(	'BE','09',N'West-Vlaanderen'),
(	'BE','10',N'Brabant (Walloon),'),
(	'BE','11',N'Brussels (Capital),'),
(	'BG','01',N'Burgas'),
(	'BG','02',N'Grad Sofiya'),
(	'BG','03',N'Khaskovo'),
(	'BG','04',N'Lovech'),
(	'BG','05',N'Montana'),
(	'BG','06',N'Plovdiv'),
(	'BG','07',N'Ruse'),
(	'BG','08',N'Sofiya'),
(	'BG','09',N'Varna'),
(	'BR','AC',N'Acre'),
(	'BR','AL',N'Alagoas'),
(	'BR','AM',N'Amazon'),
(	'BR','AP',N'Amapá'),
(	'BR','BA',N'Bahia'),
(	'BR','CE',N'Ceará'),
(	'BR','DF',N'Brasília'),
(	'BR','ES',N'Espírito Santo'),
(	'BR','GO',N'Goiás'),
(	'BR','MA',N'Maranhão'),
(	'BR','MG',N'Minas Gerais'),
(	'BR','MS',N'Mato Grosso do Sul'),
(	'BR','MT',N'Mato Grosso'),
(	'BR','PA',N'Pará'),
(	'BR','PB',N'Paraíba'),
(	'BR','PE',N'Pernambuco'),
(	'BR','PI',N'Piauí'),
(	'BR','PR',N'Paraná'),
(	'BR','RJ',N'Rio de Janeiro'),
(	'BR','RN',N'Rio Grande do Norte'),
(	'BR','RO',N'Rondônia'),
(	'BR','RR',N'Roraima'),
(	'BR','RS',N'Rio Grande do Sul'),
(	'BR','SC',N'Santa Catarina'),
(	'BR','SE',N'Sergipe'),
(	'BR','SP',N'São Paulo'),
(	'BR','TO',N'Tocantins'),
(	'BZ','BZ',N'Belize'),
(	'BZ','CY',N'Cayo'),
(	'BZ','CZ',N'Corozal'),
(	'BZ','OW',N'Orange Walk'),
(	'BZ','SC',N'Stann Creek'),
(	'BZ','TO',N'Toledo'),
(	'CA','AB',N'Alberta'),
(	'CA','BC',N'British Columbia'),
(	'CA','MB',N'Manitoba'),
(	'CA','NB',N'New Brunswick'),
(	'CA','NE',N'ACS Legacy'),
(	'CA','NF',N'Newfoundland (old),'),
(	'CA','NL',N'Newfoundland & Labr.'),
(	'CA','NS',N'Nova Scotia'),
(	'CA','NT',N'Northwest Terr.'),
(	'CA','NU',N'Nunavut'),
(	'CA','ON',N'Ontario'),
(	'CA','PE',N'Prince Edward Island'),
(	'CA','PQ',N'ACS Legacy'),
(	'CA','QC',N'Quebec'),
(	'CA','SK',N'Saskatchewan'),
(	'CA','YT',N'Yukon Territory'),
(	'CH','AG',N'Aargau'),
(	'CH','AI',N'Inner-Rhoden'),
(	'CH','AR',N'Ausser-Rhoden'),
(	'CH','BE',N'Bern'),
(	'CH','BL',N'Basel Land'),
(	'CH','BS',N'Basel Stadt'),
(	'CH','FR',N'Fribourg'),
(	'CH','GE',N'Geneva'),
(	'CH','GL',N'Glarus'),
(	'CH','GR',N'Graubuenden'),
(	'CH','JU',N'Jura'),
(	'CH','LU',N'Lucerne'),
(	'CH','NE',N'Neuchatel'),
(	'CH','NW',N'Nidwalden'),
(	'CH','OW',N'Obwalden'),
(	'CH','SG',N'St. Gallen'),
(	'CH','SH',N'Schaffhausen'),
(	'CH','SO',N'Solothurn'),
(	'CH','SZ',N'Schwyz'),
(	'CH','TG',N'Thurgau'),
(	'CH','TI',N'Ticino'),
(	'CH','UR',N'Uri'),
(	'CH','VD',N'Vaud'),
(	'CH','VS',N'Valais'),
(	'CH','ZG',N'Zug'),
(	'CH','ZH',N'Zurich'),
(	'CL','01',N'I - Iquique'),
(	'CL','02',N'II - Antofagasta'),
(	'CL','03',N'III - Copiapo'),
(	'CL','04',N'IV - La Serena'),
(	'CL','05',N'V - Valparaiso'),
(	'CL','06',N'VI - Rancagua'),
(	'CL','07',N'VII - Talca'),
(	'CL','08',N'VIII - Concepción'),
(	'CL','09',N'IX - Temuco'),
(	'CL','10',N'X - Puerto Montt'),
(	'CL','11',N'XI - Coyhaique'),
(	'CL','12',N'XII - Punta Arenas'),
(	'CL','13',N'RM - Santiago'),
(	'CN','010',N'Beijing'),
(	'CN','020',N'Shanghai'),
(	'CN','030',N'Tianjin'),
(	'CN','040',N'Nei Mongol'),
(	'CN','050',N'Shanxi'),
(	'CN','060',N'Hebei'),
(	'CN','070',N'Liaoning'),
(	'CN','080',N'Jilin'),
(	'CN','090',N'Heilongjiang'),
(	'CN','100',N'Jiangsu'),
(	'CN','110',N'Anhui'),
(	'CN','120',N'Shandong'),
(	'CN','130',N'Zhejiang'),
(	'CN','140',N'Jiangxi'),
(	'CN','150',N'Fujian'),
(	'CN','160',N'Hunan'),
(	'CN','170',N'Hubei'),
(	'CN','180',N'Henan'),
(	'CN','190',N'Guangdong'),
(	'CN','200',N'Hainan'),
(	'CN','210',N'Guangxi'),
(	'CN','220',N'Guizhou'),
(	'CN','230',N'Sichuan'),
(	'CN','240',N'Yunnan'),
(	'CN','250',N'Shaanxi'),
(	'CN','260',N'Gansu'),
(	'CN','270',N'Ningxia'),
(	'CN','280',N'Qinghai'),
(	'CN','290',N'Xinjiang'),
(	'CN','300',N'Xizang'),
(	'CN','310',N'Taiwan'),
(	'CO','05',N'ANTIOQUIA'),
(	'CO','08',N'ATLANTICO'),
(	'CO','11',N'BOGOTA'),
(	'CO','13',N'BOLIVAR'),
(	'CO','15',N'BOYACA'),
(	'CO','17',N'CALDAS'),
(	'CO','18',N'CAQUETA'),
(	'CO','19',N'CAUCA'),
(	'CO','20',N'CESAR'),
(	'CO','23',N'CORDOBA'),
(	'CO','25',N'CUNDINAMARCA'),
(	'CO','27',N'CHOCO'),
(	'CO','41',N'HUILA'),
(	'CO','44',N'LA GUAJIRA'),
(	'CO','47',N'MAGDALENA'),
(	'CO','50',N'META'),
(	'CO','52',N'NARIÑO'),
(	'CO','54',N'NORTE SANTANDER'),
(	'CO','63',N'QUINDIO'),
(	'CO','66',N'RISARALDA'),
(	'CO','68',N'SANTANDER'),
(	'CO','70',N'SUCRE'),
(	'CO','73',N'TOLIMA'),
(	'CO','76',N'VALLE'),
(	'CO','81',N'ARAUCA'),
(	'CO','85',N'CASANARE'),
(	'CO','86',N'PUTUMAYO'),
(	'CO','88',N'SAN ANDRES'),
(	'CO','91',N'AMAZONAS'),
(	'CO','94',N'GUAINIA'),
(	'CO','95',N'GUAVIARE'),
(	'CO','97',N'VAUPES'),
(	'CO','99',N'VICHADA'),
(	'CZ','01',N'Jihocesky'),
(	'CZ','02',N'Jihomoravsky'),
(	'CZ','03',N'Praha'),
(	'CZ','04',N'Severocesky'),
(	'CZ','05',N'Severomoravsky'),
(	'CZ','06',N'Stredocesky'),
(	'CZ','07',N'Vychodocesky'),
(	'CZ','08',N'Zapadocesky'),
(	'DE','01',N'Schleswig-Holstein'),
(	'DE','02',N'Hamburg'),
(	'DE','03',N'Lower Saxony'),
(	'DE','04',N'Bremen'),
(	'DE','05',N'Nrth Rhine Westfalia'),
(	'DE','06',N'Hesse'),
(	'DE','07',N'Rhineland Palatinate'),
(	'DE','08',N'Baden-Wurttemberg'),
(	'DE','09',N'Bavaria'),
(	'DE','10',N'Saarland'),
(	'DE','11',N'Berlin'),
(	'DE','12',N'Brandenburg'),
(	'DE','13',N'Mecklenburg-Vorpomm.'),
(	'DE','14',N'Saxony'),
(	'DE','15',N'Saxony-Anhalt'),
(	'DE','16',N'Thuringia'),
(	'DK','001',N'Copenhagen'),
(	'DK','002',N'Århus amt'),
(	'DK','003',N'Bornholm amt'),
(	'DK','004',N'Frederiksborg amt'),
(	'DK','005',N'Fyn amt'),
(	'DK','006',N'København amt'),
(	'DK','007',N'Nordjylland amt'),
(	'DK','008',N'Ribe amt'),
(	'DK','009',N'Ringkøbing amt'),
(	'DK','010',N'Roskilde amt'),
(	'DK','011',N'Sønderjylland amt'),
(	'DK','012',N'Storstrøm amt'),
(	'DK','013',N'Vejle amt'),
(	'DK','014',N'Vestsjælland amt'),
(	'DK','015',N'Viborg amt'),
(	'DK','016',N'Grønlands amt'),
(	'ES','01',N'Alava'),
(	'ES','02',N'Albacete'),
(	'ES','03',N'Alicante'),
(	'ES','04',N'Almeria'),
(	'ES','05',N'Avila'),
(	'ES','06',N'Badajoz'),
(	'ES','07',N'Baleares'),
(	'ES','08',N'Barcelona'),
(	'ES','09',N'Burgos'),
(	'ES','10',N'Caceres'),
(	'ES','11',N'Cadiz'),
(	'ES','12',N'Castellon'),
(	'ES','13',N'Ciudad Real'),
(	'ES','14',N'Córdoba'),
(	'ES','15',N'La Coruña'),
(	'ES','16',N'Cuenca'),
(	'ES','17',N'Gerona'),
(	'ES','18',N'Granada'),
(	'ES','19',N'Guadalajara'),
(	'ES','20',N'Guipuzcoa'),
(	'ES','21',N'Huelva'),
(	'ES','22',N'Huesca'),
(	'ES','23',N'Jaen'),
(	'ES','24',N'Leon'),
(	'ES','25',N'Lerida'),
(	'ES','26',N'La Rioja'),
(	'ES','27',N'Lugo'),
(	'ES','28',N'Madrid'),
(	'ES','29',N'Malaga'),
(	'ES','30',N'Murcia'),
(	'ES','31',N'Navarra'),
(	'ES','32',N'Orense'),
(	'ES','33',N'Asturias'),
(	'ES','34',N'Palencia'),
(	'ES','35',N'Las Palmas'),
(	'ES','36',N'Pontevedra'),
(	'ES','37',N'Salamanca'),
(	'ES','38',N'Sta. Cruz Tenerife'),
(	'ES','39',N'Cantabria'),
(	'ES','40',N'Segovia'),
(	'ES','41',N'Sevilla'),
(	'ES','42',N'Soria'),
(	'ES','43',N'Tarragona'),
(	'ES','44',N'Teruel'),
(	'ES','45',N'Toledo'),
(	'ES','46',N'Valencia'),
(	'ES','47',N'Valladolid'),
(	'ES','48',N'Vizcaya'),
(	'ES','49',N'Zamora'),
(	'ES','50',N'Zaragoza'),
(	'FI','001',N'Ahvenanmaa'),
(	'FI','002',N'Etelä-Suomi'),
(	'FI','003',N'Itä-Suomi'),
(	'FI','004',N'Lappi'),
(	'FI','005',N'Länsi-Suomi'),
(	'FI','006',N'Oulu'),
(	'FR','01',N'Ain'),
(	'FR','02',N'Aisne'),
(	'FR','03',N'Allier'),
(	'FR','04',N'Alpes (Hte-Provence),'),
(	'FR','05',N'Alpes (Hautes),'),
(	'FR','06',N'Alpes-Maritimes'),
(	'FR','07',N'Ardèche'),
(	'FR','08',N'Ardennes'),
(	'FR','09',N'Ariège'),
(	'FR','10',N'Aube'),
(	'FR','11',N'Aude'),
(	'FR','12',N'Aveyron'),
(	'FR','13',N'Bouches-du-Rhône'),
(	'FR','14',N'Calvados'),
(	'FR','15',N'Cantal'),
(	'FR','16',N'Charente'),
(	'FR','17',N'Charente-Maritime'),
(	'FR','18',N'Cher'),
(	'FR','19',N'Corrèze'),
(	'FR','21',N'Côte-d''Or'),
(	'FR','22',N'Côtes-d''Armor'),
(	'FR','23',N'Creuse'),
(	'FR','24',N'Dordogne'),
(	'FR','25',N'Doubs'),
(	'FR','26',N'Drôme'),
(	'FR','27',N'Eure'),
(	'FR','28',N'Eure-et-Loir'),
(	'FR','29',N'Finistère'),
(	'FR','2A',N'Corse-du-Sud'),
(	'FR','2B',N'Corse-du-Nord'),
(	'FR','30',N'Gard'),
(	'FR','31',N'Garonne (Haute),'),
(	'FR','32',N'Gers'),
(	'FR','33',N'Gironde'),
(	'FR','34',N'Hérault'),
(	'FR','35',N'Ille-et-Vilaine'),
(	'FR','36',N'Indre'),
(	'FR','37',N'Indre-et-Loire'),
(	'FR','38',N'Isère'),
(	'FR','39',N'Jura'),
(	'FR','40',N'Landes'),
(	'FR','41',N'Loir-et-Cher'),
(	'FR','42',N'Loire'),
(	'FR','43',N'Loire (Haute),'),
(	'FR','44',N'Loire-Atlantique'),
(	'FR','45',N'Loiret'),
(	'FR','46',N'Lot'),
(	'FR','47',N'Lot-et-Garonne'),
(	'FR','48',N'Lozère'),
(	'FR','49',N'Maine-et-Loire'),
(	'FR','50',N'Manche'),
(	'FR','51',N'Marne'),
(	'FR','52',N'Marne (Haute),'),
(	'FR','53',N'Mayenne'),
(	'FR','54',N'Meurthe-et-Moselle'),
(	'FR','55',N'Meuse'),
(	'FR','56',N'Morbihan'),
(	'FR','57',N'Moselle'),
(	'FR','58',N'Nièvre'),
(	'FR','59',N'Nord'),
(	'FR','60',N'Oise'),
(	'FR','61',N'Orne'),
(	'FR','62',N'Pas-de-Calais'),
(	'FR','63',N'Puy-de-Dôme'),
(	'FR','64',N'Pyrénées-Atlantiques'),
(	'FR','65',N'Pyrénées (Hautes),'),
(	'FR','66',N'Pyrénées-Orientales'),
(	'FR','67',N'Bas-Rhin'),
(	'FR','68',N'Haut-Rhin'),
(	'FR','69',N'Rhône'),
(	'FR','70',N'Saône (Haute),'),
(	'FR','71',N'Saône-et-Loire'),
(	'FR','72',N'Sarthe'),
(	'FR','73',N'Savoie'),
(	'FR','74',N'Savoie (Haute),'),
(	'FR','75',N'Paris'),
(	'FR','76',N'Seine-Maritime'),
(	'FR','77',N'Seine-et-Marne'),
(	'FR','78',N'Yvelines'),
(	'FR','79',N'Sèvres (Deux),'),
(	'FR','80',N'Somme'),
(	'FR','81',N'Tarn'),
(	'FR','82',N'Tarn-et-Garonne'),
(	'FR','83',N'Var'),
(	'FR','84',N'Vaucluse'),
(	'FR','85',N'Vendée'),
(	'FR','86',N'Vienne'),
(	'FR','87',N'Vienne (Haute),'),
(	'FR','88',N'Vosges'),
(	'FR','89',N'Yonne'),
(	'FR','90',N'Territ.-de-Belfort'),
(	'FR','91',N'Essonne'),
(	'FR','92',N'Hauts-de-Seine'),
(	'FR','93',N'Seine-Saint-Denis'),
(	'FR','94',N'Val-de-Marne'),
(	'FR','95',N'Val-d''Oise'),
(	'FR','97',N'D.O.M.-T.O.M.'),
(	'FR','971',N'Guadeloupe'),
(	'FR','972',N'Martinique'),
(	'FR','973',N'Guyane'),
(	'FR','974',N'Réunion'),
(	'FR','975',N'Saint-Pierre-et-Miq.'),
(	'FR','976',N'Wallis-et-Futuna'),
(	'FR','99',N'Hors-France'),
(	'GB','AM',N'Armagh'),
(	'GB','AR',N'Ards'),
(	'GB','AT',N'Antrim'),
(	'GB','BA',N'Ballymena'),
(	'GB','BB',N'Blackburn'),
(	'GB','BE',N'Bedfordshire'),
(	'GB','BF',N'Bracknell Forest'),
(	'GB','BH',N'Brighton & Hove'),
(	'GB','BK',N'Berkshire'),
(	'GB','BL',N'Belfast'),
(	'GB','BM',N'Bournemouth'),
(	'GB','BN',N'Banbridge'),
(	'GB','BO',N'Borders'),
(	'GB','BP',N'Blackpool'),
(	'GB','BR',N'Bristol'),
(	'GB','BS',N'Bath&NthEstSomerset'),
(	'GB','BU',N'Buckinghamshire'),
(	'GB','BY',N'Ballymoney'),
(	'GB','CA',N'Cambridgeshire'),
(	'GB','CE',N'Central'),
(	'GB','CG',N'Craigavon'),
(	'GB','CH',N'Cheshire'),
(	'GB','CI',N'Coleraine'),
(	'GB','CK',N'Cookstown'),
(	'GB','CL',N'Clwyd'),
(	'GB','CO',N'Cornwall'),
(	'GB','CR',N'Carrickfergus'),
(	'GB','CS',N'Castlereagh'),
(	'GB','CU',N'Cumbria'),
(	'GB','CV',N'Cleveland'),
(	'GB','DB',N'Derbyshire'),
(	'GB','DF',N'Dumfries a. Galloway'),
(	'GB','DG',N'Dungannon'),
(	'GB','DL',N'Darlington'),
(	'GB','DN',N'Down'),
(	'GB','DO',N'Dorset'),
(	'GB','DU',N'Durham'),
(	'GB','DV',N'Devon'),
(	'GB','DY',N'Dyfed'),
(	'GB','ER',N'East Riding'),
(	'GB','ES',N'Essex'),
(	'GB','FI',N'Fife'),
(	'GB','FM',N'Fermanagh'),
(	'GB','GL',N'Gloucestershire'),
(	'GB','GM',N'Greater Manchester'),
(	'GB','GR',N'Grampian'),
(	'GB','GS',N'Sth. Gloucestershire'),
(	'GB','GW',N'Gwent'),
(	'GB','GY',N'Gwynedd'),
(	'GB','HA',N'Hampshire'),
(	'GB','HI',N'Highland'),
(	'GB','HL',N'Halton'),
(	'GB','HR',N'Hartlepool'),
(	'GB','HT',N'Hertfordshire'),
(	'GB','HW',N'Hereford and Worcs.'),
(	'GB','IW',N'Isle of Wight'),
(	'GB','KE',N'Kent'),
(	'GB','KH',N'Kingston-upon-Hull'),
(	'GB','LA',N'Lancashire'),
(	'GB','LC',N'Leicester City'),
(	'GB','LD',N'Londonderry'),
(	'GB','LE',N'Leicestershire'),
(	'GB','LI',N'Lincolnshire'),
(	'GB','LM',N'Limavady'),
(	'GB','LO',N'Greater London'),
(	'GB','LR',N'Larne'),
(	'GB','LS',N'Lisburn'),
(	'GB','LT',N'Lothian'),
(	'GB','LU',N'Luton'),
(	'GB','MA',N'Magherafelt'),
(	'GB','MG',N'Mid Glamorgan'),
(	'GB','MI',N'Middlesbrough'),
(	'GB','MK',N'Milton Keynes'),
(	'GB','MO',N'Moyle'),
(	'GB','MY',N'Merseyside'),
(	'GB','NA',N'Newtownabbey'),
(	'GB','NB',N'Newbury'),
(	'GB','NC',N'Nottingham City'),
(	'GB','ND',N'North Down'),
(	'GB','NE',N'NthEast Lincolnshire'),
(	'GB','NH',N'Northamptonshire'),
(	'GB','NK',N'Norfolk'),
(	'GB','NL',N'North Lincolnshire'),
(	'GB','NM',N'Newry and Mourne'),
(	'GB','NS',N'North Somerset'),
(	'GB','NT',N'Nottinghamshire'),
(	'GB','NU',N'Northumberland'),
(	'GB','OM',N'Omagh'),
(	'GB','OR',N'Orkney'),
(	'GB','OX',N'Oxfordshire'),
(	'GB','PB',N'Peterborough'),
(	'GB','PL',N'Poole'),
(	'GB','PM',N'Portsmouth'),
(	'GB','PO',N'Powys'),
(	'GB','PY',N'Plymouth'),
(	'GB','RD',N'Redcar and Cleveland'),
(	'GB','RE',N'Reading'),
(	'GB','RM',N'Rochester up. Medway'),
(	'GB','RU',N'Rutland'),
(	'GB','SC',N'Strathclyde'),
(	'GB','SD',N'Southend'),
(	'GB','SE',N'East Sussex'),
(	'GB','SG',N'South Glamorgan'),
(	'GB','SH',N'Shropshire'),
(	'GB','SK',N'Suffolk'),
(	'GB','SL',N'Shetland'),
(	'GB','SN',N'Stockton-on-Tees'),
(	'GB','SO',N'Somerset'),
(	'GB','SP',N'Southampton'),
(	'GB','SR',N'Strabane'),
(	'GB','ST',N'Staffordshire'),
(	'GB','SU',N'Slough'),
(	'GB','SW',N'West Sussex'),
(	'GB','SY',N'Surrey'),
(	'GB','TA',N'Tayside'),
(	'GB','TD',N'Thamesdown'),
(	'GB','TH',N'Thurrock'),
(	'GB','TO',N'Torbay'),
(	'GB','TW',N'Tyne and Wear'),
(	'GB','WA',N'Warwickshire'),
(	'GB','WD',N'Windsor & Maidenhead'),
(	'GB','WG',N'West Glamorgan'),
(	'GB','WI',N'Wiltshire'),
(	'GB','WL',N'Western Isles'),
(	'GB','WM',N'West Midlands'),
(	'GB','WO',N'Wokingham'),
(	'GB','WR',N'Wrekin'),
(	'GB','WT',N'Warrington'),
(	'GB','YK',N'York'),
(	'GB','YN',N'North Yorkshire'),
(	'GB','YS',N'South Yorkshire'),
(	'GB','YW',N'West Yorkshire'),
(	'GR','01',N'Aitolia kai Akarnan.'),
(	'GR','02',N'Akhaia'),
(	'GR','03',N'Argolis'),
(	'GR','04',N'Arkadhia'),
(	'GR','05',N'Arta'),
(	'GR','06',N'Attiki'),
(	'GR','07',N'Dhodhekanisos'),
(	'GR','08',N'Dhrama'),
(	'GR','09',N'Evritania'),
(	'GR','10',N'Evros'),
(	'GR','11',N'Evvoia'),
(	'GR','12',N'Florina'),
(	'GR','13',N'Fokis'),
(	'GR','14',N'Fthiotis'),
(	'GR','15',N'Grevena'),
(	'GR','16',N'Ilia'),
(	'GR','17',N'Imathia'),
(	'GR','18',N'Ioannina'),
(	'GR','19',N'Iraklion'),
(	'GR','20',N'Kardhitsa'),
(	'GR','21',N'Kastoria'),
(	'GR','22',N'Kavala'),
(	'GR','23',N'Kefallinia'),
(	'GR','24',N'Kerkira'),
(	'GR','25',N'Khalkidhiki'),
(	'GR','26',N'Khania'),
(	'GR','27',N'Khios'),
(	'GR','28',N'Kikladhes'),
(	'GR','29',N'Kilkis'),
(	'GR','30',N'Korinthia'),
(	'GR','31',N'Kozani'),
(	'GR','32',N'Lakonia'),
(	'GR','33',N'Larisa'),
(	'GR','34',N'Lasithi'),
(	'GR','35',N'Lesvos'),
(	'GR','36',N'Levkas'),
(	'GR','37',N'Magnisia'),
(	'GR','38',N'Messinia'),
(	'GR','39',N'Pella'),
(	'GR','40',N'Pieria'),
(	'GR','41',N'Piraievs'),
(	'GR','42',N'Preveza'),
(	'GR','43',N'Rethimni'),
(	'GR','44',N'Rodhopi'),
(	'GR','45',N'Samos'),
(	'GR','46',N'Serrai'),
(	'GR','47',N'Thesprotia'),
(	'GR','48',N'Thessaloniki'),
(	'GR','49',N'Trikala'),
(	'GR','50',N'Voiotia'),
(	'GR','51',N'Xanthi'),
(	'GR','52',N'Zakinthos'),
(	'HK','HK',N'Hong Kong Island'),
(	'HK','KLN',N'Kowloon'),
(	'HK','NT',N'New Territories'),
(	'HN','AT',N'Atlántida'),
(	'HN','CH',N'Choluteca'),
(	'HN','CL',N'Colón'),
(	'HN','CM',N'Comayagua'),
(	'HN','CP',N'Copán'),
(	'HN','CR',N'Cortés'),
(	'HN','EP',N'El Paraíso'),
(	'HN','FM',N'Francisco Morazán'),
(	'HN','GD',N'Gracias a Dios'),
(	'HN','IB',N'Islas de la Bahía'),
(	'HN','IN',N'Intibucá'),
(	'HN','LE',N'Lempira'),
(	'HN','LP',N'La Paz'),
(	'HN','OC',N'Ocotepeque'),
(	'HN','OL',N'Olancho'),
(	'HN','SB',N'Santa Bárbara'),
(	'HN','VA',N'Valle'),
(	'HN','YO',N'Yoro'),
(	'HR','01',N'Bjelovar-Bilogora'),
(	'HR','02',N'Stadt Zagreb'),
(	'HR','03',N'Dubrovnik-Neretva'),
(	'HR','04',N'Istra'),
(	'HR','05',N'Karlovac'),
(	'HR','06',N'Koprivnica-Krizevci'),
(	'HR','07',N'Lika-Senj'),
(	'HR','08',N'Medimurje'),
(	'HR','09',N'Osijek-Baranja'),
(	'HR','10',N'Pozega-Slavonija'),
(	'HR','11',N'Primorje-Gorski Kot.'),
(	'HR','12',N'Sibenik'),
(	'HR','13',N'Sisak-Moslavina'),
(	'HR','14',N'Slavonski'),
(	'HR','15',N'Brod-Posavina'),
(	'HR','16',N'Split-Dalmatia'),
(	'HR','17',N'Varazdin'),
(	'HR','18',N'Virovitica-Podravina'),
(	'HR','19',N'Vukovar-Srijem'),
(	'HR','20',N'Zadar-Knin'),
(	'HR','21',N'Zagreb'),
(	'HU','01',N'Bacs-Kiskun'),
(	'HU','02',N'Baranya'),
(	'HU','03',N'Bekes'),
(	'HU','04',N'Bekescsaba'),
(	'HU','05',N'Borsod-Abauj-Zemplen'),
(	'HU','06',N'Budapest'),
(	'HU','07',N'Csongrad'),
(	'HU','08',N'Debrecen'),
(	'HU','09',N'Dunaujvaros'),
(	'HU','10',N'Eger'),
(	'HU','11',N'Fejer'),
(	'HU','12',N'Gyor'),
(	'HU','13',N'Gyor-Moson-Sopron'),
(	'HU','14',N'Hajdu-Bihar'),
(	'HU','15',N'Heves'),
(	'HU','16',N'Hodmezovasarhely'),
(	'HU','17',N'Jasz-Nagykun-Szolnok'),
(	'HU','18',N'Kaposvar'),
(	'HU','19',N'Kecskemet'),
(	'HU','20',N'Komarom-Esztergom'),
(	'HU','21',N'Miskolc'),
(	'HU','22',N'Nagykanizsa'),
(	'HU','23',N'Nograd'),
(	'HU','24',N'Nyiregyhaza'),
(	'HU','25',N'Pecs'),
(	'HU','26',N'Pest'),
(	'HU','27',N'Somogy'),
(	'HU','28',N'Sopron'),
(	'HU','29',N'Szabolcs-Szat.-Bereg'),
(	'HU','30',N'Szeged'),
(	'HU','31',N'Szekesfehervar'),
(	'HU','32',N'Szolnok'),
(	'HU','33',N'Szombathely'),
(	'HU','34',N'Tatabanya'),
(	'HU','35',N'Tolna'),
(	'HU','36',N'Vas'),
(	'HU','37',N'Veszprem'),
(	'HU','38',N'Zala'),
(	'HU','39',N'Zalaegerszeg'),
(	'ID','01',N'DKI Jakarta Jakarta'),
(	'ID','02',N'Jawa Barat West Java'),
(	'ID','03',N'Jawa Tengah Central'),
(	'ID','04',N'Jawa Timur East Java'),
(	'ID','05',N'DI Yogyakarta Yogyak'),
(	'ID','06',N'DI Aceh Aceh'),
(	'ID','07',N'Sumatera Utara North'),
(	'ID','08',N'Sumatera Barat West'),
(	'ID','09',N'Riau Riau'),
(	'ID','10',N'Jambi Jambi'),
(	'ID','11',N'Sumatera Selatan Sou'),
(	'ID','12',N'Bengkulu Bengkulu'),
(	'ID','13',N'Lampung Lampung'),
(	'ID','14',N'Kalimantan Selatan S'),
(	'ID','15',N'Kalimantan Barat Wes'),
(	'ID','16',N'Kalimantan Tengah Ce'),
(	'ID','17',N'Kalimantan Timur Eas'),
(	'ID','18',N'Sulawesi Selatan Sou'),
(	'ID','19',N'Sulawesi Tenggara So'),
(	'ID','20',N'Sulawesi Tengah Cent'),
(	'ID','21',N'Sulawesi Utara North'),
(	'ID','22',N'Bali Bali'),
(	'ID','23',N'Nusa Tenggara Barat'),
(	'ID','24',N'Nusa Tenggara Timur'),
(	'ID','25',N'Maluku Maluku'),
(	'ID','26',N'Irian Jaya Irian Jay'),
(	'ID','27',N'Timor Timur East Tim'),
(	'IE','CK',N'Cork'),
(	'IE','CL',N'Clare'),
(	'IE','CV',N'Cavan'),
(	'IE','CW',N'Carlow'),
(	'IE','DB',N'Dublin'),
(	'IE','DG',N'Donegal'),
(	'IE','GW',N'Galway'),
(	'IE','KD',N'Kildare'),
(	'IE','KK',N'Kilkenny'),
(	'IE','KY',N'Kerry'),
(	'IE','LF',N'Longford'),
(	'IE','LI',N'Limerick'),
(	'IE','LM',N'Leitrim'),
(	'IE','LS',N'Laois'),
(	'IE','LT',N'Louth'),
(	'IE','MH',N'Monaghan'),
(	'IE','MT',N'Meath'),
(	'IE','MY',N'Mayo'),
(	'IE','OF',N'Offaly'),
(	'IE','RC',N'Rosscommon'),
(	'IE','SG',N'Sligo'),
(	'IE','TP',N'Tipperary'),
(	'IE','WF',N'Waterford'),
(	'IE','WK',N'Wicklow'),
(	'IE','WM',N'Westmeath'),
(	'IE','WX',N'Wexford'),
(	'IL','01',N'Central'),
(	'IL','02',N'Haifa'),
(	'IL','03',N'Jerusalem'),
(	'IL','04',N'Northern'),
(	'IL','05',N'Southern'),
(	'IL','06',N'Tel Aviv'),
(	'IN','01',N'Andra Pradesh'),
(	'IN','02',N'Arunachal Pradesh'),
(	'IN','03',N'Assam'),
(	'IN','04',N'Bihar'),
(	'IN','05',N'Goa'),
(	'IN','06',N'Gujarat'),
(	'IN','07',N'Haryana'),
(	'IN','08',N'Himachal Pradesh'),
(	'IN','09',N'Jammu und Kashmir'),
(	'IN','10',N'Karnataka'),
(	'IN','11',N'Kerala'),
(	'IN','12',N'Madhya Pradesh'),
(	'IN','13',N'Maharashtra'),
(	'IN','14',N'Manipur'),
(	'IN','15',N'Megalaya'),
(	'IN','16',N'Mizoram'),
(	'IN','17',N'Nagaland'),
(	'IN','18',N'Orissa'),
(	'IN','19',N'Punjab'),
(	'IN','20',N'Rajasthan'),
(	'IN','21',N'Sikkim'),
(	'IN','22',N'Tamil Nadu'),
(	'IN','23',N'Tripura'),
(	'IN','24',N'Uttar Pradesh'),
(	'IN','25',N'West Bengal'),
(	'IN','26',N'Andaman und Nico.In.'),
(	'IN','27',N'Chandigarh'),
(	'IN','28',N'Dadra und Nagar Hav.'),
(	'IN','29',N'Daman und Diu'),
(	'IN','30',N'Delhi'),
(	'IN','31',N'Lakshadweep'),
(	'IN','32',N'Pondicherry'),
(	'IN','33',N'Pondicherry'),
(	'IN','34',N''),
(	'IN','35',N''),
(	'IT','AG',N'Agriento'),
(	'IT','AL',N'Alessandria'),
(	'IT','AN',N'Ancona'),
(	'IT','AO',N'Aosta'),
(	'IT','AP',N'Ascoli Piceno'),
(	'IT','AQ',N'L''Aquila'),
(	'IT','AR',N'Arezzo'),
(	'IT','AT',N'Asti'),
(	'IT','AV',N'Avellino'),
(	'IT','BA',N'Bari'),
(	'IT','BG',N'Bergamo'),
(	'IT','BI',N'Biella'),
(	'IT','BL',N'Belluno'),
(	'IT','BN',N'Benevento'),
(	'IT','BO',N'Bologna'),
(	'IT','BR',N'Brindisi'),
(	'IT','BS',N'Brescia'),
(	'IT','BZ',N'Bolzano'),
(	'IT','CA',N'Cagliari'),
(	'IT','CB',N'Campobasso'),
(	'IT','CE',N'Caserta'),
(	'IT','CH',N'Chieti'),
(	'IT','CL',N'Caltanisetta'),
(	'IT','CN',N'Cuneo'),
(	'IT','CO',N'Como'),
(	'IT','CR',N'Cremona'),
(	'IT','CS',N'Cosenza'),
(	'IT','CT',N'Catania'),
(	'IT','CZ',N'Catanzaro'),
(	'IT','EN',N'Enna'),
(	'IT','FE',N'Ferrara'),
(	'IT','FG',N'Foggia'),
(	'IT','FI',N'Florence'),
(	'IT','FO',N'Forlì'),
(	'IT','FR',N'Frosinone'),
(	'IT','GE',N'Genova'),
(	'IT','GO',N'Gorizia'),
(	'IT','GR',N'Grosseto'),
(	'IT','IM',N'Imperia'),
(	'IT','IS',N'Isernia'),
(	'IT','KR',N'Crotone'),
(	'IT','LC',N'Lecco'),
(	'IT','LE',N'Lecce'),
(	'IT','LI',N'Livorno'),
(	'IT','LO',N'Lodi'),
(	'IT','LT',N'Latina'),
(	'IT','LU',N'Lucca'),
(	'IT','MC',N'Macerata'),
(	'IT','ME',N'Messina'),
(	'IT','MI',N'Milan'),
(	'IT','MN',N'Mantova'),
(	'IT','MO',N'Modena'),
(	'IT','MS',N'Massa Carrara'),
(	'IT','MT',N'Matera'),
(	'IT','NA',N'Naples'),
(	'IT','NO',N'Novara'),
(	'IT','NU',N'Nuoro'),
(	'IT','OR',N'Oristano'),
(	'IT','PA',N'Palermo'),
(	'IT','PC',N'Piacenza'),
(	'IT','PD',N'Padova'),
(	'IT','PE',N'Pescara'),
(	'IT','PG',N'Perugia'),
(	'IT','PI',N'Pisa'),
(	'IT','PN',N'Pordenone'),
(	'IT','PO',N'Prato'),
(	'IT','PR',N'Parma'),
(	'IT','PS',N'Pesaro'),
(	'IT','PT',N'Pistoia'),
(	'IT','PU',N'Pesaro-Urbino'),
(	'IT','PV',N'Pavia'),
(	'IT','PZ',N'Potenza'),
(	'IT','RA',N'Ravenna'),
(	'IT','RC',N'Reggio Calabria'),
(	'IT','RE',N'Reggio Emilia'),
(	'IT','RG',N'Ragusa'),
(	'IT','RI',N'Rieti'),
(	'IT','RM',N'Rome'),
(	'IT','RN',N'Rimini'),
(	'IT','RO',N'Rovigo'),
(	'IT','RV',N'Rovigo'),
(	'IT','SA',N'Salerno'),
(	'IT','SI',N'Siena'),
(	'IT','SO',N'Sondrio'),
(	'IT','SP',N'La Spezia'),
(	'IT','SR',N'Siracusa'),
(	'IT','SS',N'Sassari'),
(	'IT','SV',N'Savona'),
(	'IT','TA',N'Taranto'),
(	'IT','TE',N'Teramo'),
(	'IT','TN',N'Trento'),
(	'IT','TO',N'Turin'),
(	'IT','TP',N'Trapani'),
(	'IT','TR',N'Terni'),
(	'IT','TS',N'Trieste'),
(	'IT','TV',N'Treviso'),
(	'IT','UD',N'Udine'),
(	'IT','VA',N'Varese'),
(	'IT','VC',N'Vercelli'),
(	'IT','VE',N'Venice'),
(	'IT','VI',N'Vicenza'),
(	'IT','VR',N'Verona'),
(	'IT','VT',N'Viterbo'),
(	'IT','VV',N'Vibo Valentia'),
(	'JP','01',N'Hokkaido'),
(	'JP','02',N'Aomori'),
(	'JP','03',N'Iwate'),
(	'JP','04',N'Miyagi'),
(	'JP','05',N'Akita'),
(	'JP','06',N'Yamagata'),
(	'JP','07',N'Fukushima'),
(	'JP','08',N'Ibaraki'),
(	'JP','09',N'Tochigi'),
(	'JP','10',N'Gunma'),
(	'JP','11',N'Saitama'),
(	'JP','12',N'Chiba'),
(	'JP','13',N'Tokyo'),
(	'JP','14',N'Kanagawa'),
(	'JP','15',N'Niigata'),
(	'JP','16',N'Toyama'),
(	'JP','17',N'Ishikawa'),
(	'JP','18',N'Fukui'),
(	'JP','19',N'Yamanashi'),
(	'JP','20',N'Nagano'),
(	'JP','21',N'Gifu'),
(	'JP','22',N'Shizuoka'),
(	'JP','23',N'Aichi'),
(	'JP','24',N'Mie'),
(	'JP','25',N'Shiga'),
(	'JP','26',N'Kyoto'),
(	'JP','27',N'Osaka'),
(	'JP','28',N'Hyogo'),
(	'JP','29',N'Nara'),
(	'JP','30',N'Wakayama'),
(	'JP','31',N'Tottori'),
(	'JP','32',N'Shimane'),
(	'JP','33',N'Okayama'),
(	'JP','34',N'Hiroshima'),
(	'JP','35',N'Yamaguchi'),
(	'JP','36',N'Tokushima'),
(	'JP','37',N'Kagawa'),
(	'JP','38',N'Ehime'),
(	'JP','39',N'Kochi'),
(	'JP','40',N'Fukuoka'),
(	'JP','41',N'Saga'),
(	'JP','42',N'Nagasaki'),
(	'JP','43',N'Kumamoto'),
(	'JP','44',N'Oita'),
(	'JP','45',N'Miyazaki'),
(	'JP','46',N'Kagoshima'),
(	'JP','47',N'Okinawa'),
(	'KR','01',N'Cheju-do'),
(	'KR','02',N'Cholla-bukto'),
(	'KR','03',N'Cholla-namdo'),
(	'KR','04',N'Ch´ungch´ong-bukto'),
(	'KR','05',N'Ch´ungch´ong-namdo'),
(	'KR','06',N'Inch´on-jikhalsi'),
(	'KR','07',N'Kangwon-do'),
(	'KR','08',N'Kwangju-jikhalsi'),
(	'KR','09',N'Kyonggi-do'),
(	'KR','10',N'Kyongsang-bukto'),
(	'KR','11',N'Kyongsang-namdo'),
(	'KR','12',N'Pusan-jikhalsi'),
(	'KR','13',N'Soul-t´ukpyolsi'),
(	'KR','14',N'Taegu-jikhalsi'),
(	'KR','15',N'Taejon-jikhalsi'),
(	'KZ','00',N'Almatynskaia'),
(	'KZ','01',N'Kostanaiskaia'),
(	'KZ','02',N'Severo-Kazakhstansk'),
(	'KZ','03',N'Pavlodarskaia'),
(	'KZ','04',N'Akmolinskaia'),
(	'KZ','05',N'Aktubinskaia'),
(	'KZ','06',N'Atyrauskaia'),
(	'KZ','07',N'Zapadno-Kazakhst'),
(	'KZ','08',N'Mangystayskaia'),
(	'KZ','09',N'Karagandinskaia'),
(	'KZ','10',N'Vostochno-Kazakhstan'),
(	'KZ','11',N'Gambilskaia'),
(	'KZ','12',N'Kyzilordinskaia'),
(	'MX','AGS',N'Aguascalientes'),
(	'MX','AGU',N'Aguascalientes'),
(	'MX','BCN',N'Baja California (N),'),
(	'MX','BCS',N'Baja California Sur'),
(	'MX','CAM',N'Campeche'),
(	'MX','CHH',N'Chihuahua'),
(	'MX','CHI',N'Chihuahua'),
(	'MX','CHP',N'Chiapas'),
(	'MX','CHS',N'Chiapas'),
(	'MX','CMP',N'Campeche'),
(	'MX','COA',N'Coahuila'),
(	'MX','COL',N'Colima'),
(	'MX','DF',N'Distrito Federal'),
(	'MX','DGO',N'Durango'),
(	'MX','DIF',N'Distrito Federal'),
(	'MX','DUR',N'Durango'),
(	'MX','GRO',N'Guerrero'),
(	'MX','GTO',N'Guanajuato'),
(	'MX','GUA',N'Guanajuato'),
(	'MX','HGO',N'Hidalgo'),
(	'MX','HID',N'Hidalgo'),
(	'MX','JAL',N'Jalisco'),
(	'MX','MCH',N'Michoacán'),
(	'MX','MEX',N'Estado de México'),
(	'MX','MIC',N'Michoacán'),
(	'MX','MOR',N'Morelos'),
(	'MX','NAY',N'Nayarit');
INSERT INTO #CountryState ([CountryCode], [StateCode], [StateName])
VALUES 
(	'MX','NL',N'Nuevo Léon'),
(	'MX','NLE',N'Nuevo Léon'),
(	'MX','OAX',N'Oaxaca'),
(	'MX','PUE',N'Puebla'),
(	'MX','QR',N'Quintana Roo'),
(	'MX','QRO',N'Querétaro'),
(	'MX','QUE',N'Querétaro'),
(	'MX','ROO',N'Quintana Roo'),
(	'MX','SIN',N'Sinaloa'),
(	'MX','SLP',N'San Luis Potosí'),
(	'MX','SON',N'Sonora'),
(	'MX','TAB',N'Tabasco'),
(	'MX','TAM',N'Tamaulipas'),
(	'MX','TLA',N'Tlaxcala'),
(	'MX','TLX',N'Tlaxcala'),
(	'MX','TMS',N'Tamaulipas'),
(	'MX','VER',N'Veracruz'),
(	'MX','YUC',N'Yucatán'),
(	'MX','ZAC',N'Zacatecas'),
(	'MY','JOH',N'Johor'),
(	'MY','KED',N'Kedah'),
(	'MY','KEL',N'Kelantan'),
(	'MY','KUL',N'Kuala Lumpur'),
(	'MY','LAB',N'Labuan'),
(	'MY','MEL',N'Melaka'),
(	'MY','PAH',N'Pahang'),
(	'MY','PEL',N'Perlis'),
(	'MY','PER',N'Perak'),
(	'MY','PIN',N'Pulau Pinang'),
(	'MY','SAB',N'Sabah'),
(	'MY','SAR',N'Sarawak'),
(	'MY','SEL',N'Selangor'),
(	'MY','SER',N'Negeri Sembilan'),
(	'MY','TRE',N'Trengganu'),
(	'NL','01',N'Drenthe'),
(	'NL','02',N'Flevoland'),
(	'NL','03',N'Friesland'),
(	'NL','04',N'Gelderland'),
(	'NL','05',N'Groningen'),
(	'NL','06',N'Limburg'),
(	'NL','07',N'Noord-Brabant'),
(	'NL','08',N'Noord-Holland'),
(	'NL','09',N'Overijssel'),
(	'NL','10',N'Utrecht'),
(	'NL','11',N'Zeeland'),
(	'NL','12',N'Zuid-Holland'),
(	'NO','01',N'Østfold Fylke'),
(	'NO','02',N'Akershus Fylke'),
(	'NO','03',N'Oslo'),
(	'NO','04',N'Hedmark Fylke'),
(	'NO','05',N'Oppland Fylke'),
(	'NO','06',N'Buskerud Fylke'),
(	'NO','07',N'Vestfold Fylke'),
(	'NO','08',N'Telemark Fylke'),
(	'NO','09',N'Aust-Agder Fylke'),
(	'NO','10',N'Vest-Agder Fylke'),
(	'NO','11',N'Rogaland Fylke'),
(	'NO','12',N'Hordaland Fylke'),
(	'NO','14',N'Sogn og Fjordane F.'),
(	'NO','15',N'Møre og Romsdal F.'),
(	'NO','16',N'Sør-Trøndelag Fylke'),
(	'NO','17',N'Nord-Trøndelag Fylke'),
(	'NO','18',N'Nordland Fylke'),
(	'NO','19',N'Troms Fylke'),
(	'NO','20',N'Finnmark Fylke'),
(	'NZ','AKL',N'Auckland'),
(	'NZ','BOP',N'Bay of Plenty'),
(	'NZ','CAN',N'Canterbury'),
(	'NZ','HAB',N'Hawke´s Bay'),
(	'NZ','MAN',N'Manawatu-Wanganui'),
(	'NZ','NTL',N'Northland'),
(	'NZ','OTA',N'Otago'),
(	'NZ','STL',N'Southland'),
(	'NZ','TAR',N'Taranaki'),
(	'NZ','WAI',N'Waikato'),
(	'NZ','WEC',N'West Coast'),
(	'NZ','WLG',N'Wellington'),
(	'PE','01',N'Tumbes'),
(	'PE','02',N'Piura'),
(	'PE','03',N'Lambayeque'),
(	'PE','04',N'La Libertad'),
(	'PE','05',N'Ancash'),
(	'PE','06',N'Lima y Callao'),
(	'PE','07',N'Ica'),
(	'PE','08',N'Arequipa'),
(	'PE','09',N'Moquegua'),
(	'PE','10',N'Tacna'),
(	'PE','11',N'Amazon'),
(	'PE','12',N'Cajamarca'),
(	'PE','13',N'San Martín'),
(	'PE','14',N'Huánuco'),
(	'PE','15',N'Pasco'),
(	'PE','16',N'Junín'),
(	'PE','17',N'Huancavelica'),
(	'PE','18',N'Ayacucho'),
(	'PE','19',N'Apurimac'),
(	'PE','20',N'Cuzco'),
(	'PE','21',N'Puno'),
(	'PE','22',N'Loreto'),
(	'PE','23',N'Ucayali'),
(	'PE','24',N'Madre de Díos'),
(	'PH','01',N'Ilocos'),
(	'PH','02',N'Cagayan Valley'),
(	'PH','03',N'Central Luzon'),
(	'PH','04',N'South Luzon'),
(	'PH','05',N'Bicol'),
(	'PH','06',N'West Visayas'),
(	'PH','07',N'Central Visayas'),
(	'PH','08',N'Eastern Visayas'),
(	'PH','09',N'Western Mindanao'),
(	'PH','10',N'Northern Mindanao'),
(	'PH','11',N'Central Mindanao'),
(	'PH','12',N'South Mindanao'),
(	'PL','01',N'Biala Podlaska'),
(	'PL','02',N'Bialystok'),
(	'PL','03',N'Bielsko Biala'),
(	'PL','04',N'Bydgoszcz'),
(	'PL','05',N'Chelm'),
(	'PL','06',N'Ciechanow'),
(	'PL','07',N'Czestochowa'),
(	'PL','08',N'Elblag'),
(	'PL','09',N'Gdansk'),
(	'PL','10',N'Gorzow'),
(	'PL','11',N'Jelenia Gora'),
(	'PL','12',N'Kalisz'),
(	'PL','13',N'Katowice'),
(	'PL','14',N'Kielce'),
(	'PL','15',N'Konin'),
(	'PL','16',N'Koszalin'),
(	'PL','17',N'Krakow'),
(	'PL','18',N'Krosno'),
(	'PL','19',N'Legnica'),
(	'PL','20',N'Leszno'),
(	'PL','21',N'Lodz'),
(	'PL','22',N'Lomza'),
(	'PL','23',N'Lublin'),
(	'PL','24',N'Nowy Sacz'),
(	'PL','25',N'Olsztyn'),
(	'PL','26',N'Opole'),
(	'PL','27',N'Ostroleka'),
(	'PL','28',N'Pila'),
(	'PL','29',N'Piotrkow'),
(	'PL','30',N'Plock'),
(	'PL','31',N'Poznan'),
(	'PL','32',N'Przemysl'),
(	'PL','33',N'Radom'),
(	'PL','34',N'Rzeszow'),
(	'PL','35',N'Siedlce'),
(	'PL','36',N'Sieradz'),
(	'PL','37',N'Skierniewice'),
(	'PL','38',N'Slupsk'),
(	'PL','39',N'Suwalki'),
(	'PL','40',N'Szczecin'),
(	'PL','41',N'Tarnobrzeg'),
(	'PL','42',N'Tarnow'),
(	'PL','43',N'Torun'),
(	'PL','44',N'Walbrzych'),
(	'PL','45',N'Warszawa'),
(	'PL','46',N'Wloclawek'),
(	'PL','47',N'Wroclaw'),
(	'PL','48',N'Zamosc'),
(	'PL','49',N'Zielona Gora'),
(	'PT','10',N'Minho-Lima'),
(	'PT','11',N'Cávado'),
(	'PT','12',N'Ave'),
(	'PT','13',N'Grande Porto'),
(	'PT','14',N'Tâmega'),
(	'PT','15',N'Entre Douro e Vouga'),
(	'PT','16',N'Douro'),
(	'PT','17',N'Alto Trás-os-Montes'),
(	'PT','20',N'Baixo Vouga'),
(	'PT','21',N'Baixo Mondego'),
(	'PT','22',N'Pinhal Litoral'),
(	'PT','23',N'Pinhal Interior N.'),
(	'PT','24',N'Pinhal Interior Sul'),
(	'PT','25',N'Dão-Lafoes'),
(	'PT','26',N'Serra da Estrela'),
(	'PT','27',N'Beira Interior Norte'),
(	'PT','28',N'Beira Interior Sul'),
(	'PT','29',N'Cova da Beira'),
(	'PT','30',N'Oeste'),
(	'PT','31',N'Grande Lisboa'),
(	'PT','32',N'Península de Setúbal'),
(	'PT','33',N'Médio Tejo'),
(	'PT','34',N'Lezíria do Tejo'),
(	'PT','40',N'Alentejo Litoral'),
(	'PT','41',N'Alto Alentejo'),
(	'PT','42',N'Alentejo Central'),
(	'PT','43',N'Baixo Alentejo'),
(	'PT','50',N'Algarve'),
(	'PT','60',N'Reg. Aut. dos Açores'),
(	'PT','70',N'Reg. Aut. da Madeira'),
(	'RO','01',N'Alba'),
(	'RO','02',N'Arad'),
(	'RO','03',N'Arges'),
(	'RO','04',N'Bacau'),
(	'RO','05',N'Bihor'),
(	'RO','06',N'Bistrita-Nasaud'),
(	'RO','07',N'Botosani'),
(	'RO','08',N'Braila'),
(	'RO','09',N'Brasov'),
(	'RO','10',N'Bucuresti'),
(	'RO','11',N'Buzau'),
(	'RO','12',N'Calarasi'),
(	'RO','13',N'Caras-Severin'),
(	'RO','14',N'Cluj'),
(	'RO','15',N'Constanta'),
(	'RO','16',N'Covasna'),
(	'RO','17',N'Dimbovita'),
(	'RO','18',N'Dolj'),
(	'RO','19',N'Galati'),
(	'RO','20',N'Gorj'),
(	'RO','21',N'Giurgiu'),
(	'RO','22',N'Harghita'),
(	'RO','23',N'Hunedoara'),
(	'RO','24',N'Ialomita'),
(	'RO','25',N'Iasi'),
(	'RO','26',N'Maramures'),
(	'RO','27',N'Mehedinti'),
(	'RO','28',N'Mures'),
(	'RO','29',N'Neamt'),
(	'RO','30',N'Olt'),
(	'RO','31',N'Prahova'),
(	'RO','32',N'Salaj'),
(	'RO','33',N'Satu Mare'),
(	'RO','34',N'Sibiu'),
(	'RO','35',N'Suceava'),
(	'RO','36',N'Teleorman'),
(	'RO','37',N'Timis'),
(	'RO','38',N'Tulcea'),
(	'RO','39',N'Vaslui'),
(	'RO','40',N'Vilcea'),
(	'RO','41',N'Vrancea'),
(	'RU','01',N'Adigeja Republic'),
(	'RU','02',N'Highlands-Altay Rep.'),
(	'RU','03',N'Republ.of Bashkortos'),
(	'RU','04',N'Buryat Republic'),
(	'RU','05',N'Dagestan Republic'),
(	'RU','06',N'Ingushetija Republic'),
(	'RU','07',N'Kabardino-Balkar.Rep'),
(	'RU','08',N'Kalmyk Republic'),
(	'RU','09',N'Karach.-Cherkessk Re'),
(	'RU','10',N'Karelian Republic'),
(	'RU','11',N'Komi Republic'),
(	'RU','12',N'Marijskaya Republic'),
(	'RU','13',N'Mordovian Republic'),
(	'RU','14',N'Yakutiya-Saha Rrepub'),
(	'RU','15',N'North-Osetiya Republ'),
(	'RU','16',N'Tatarstan Republic'),
(	'RU','17',N'Tuva Republic'),
(	'RU','18',N'The Udmurt Republic'),
(	'RU','19',N'Chakassky Republic'),
(	'RU','20',N'Chechenskaya Republ.'),
(	'RU','21',N'Chuvash Republic'),
(	'RU','22',N'Altay Territory'),
(	'RU','23',N'Krasnodar Territory'),
(	'RU','24',N'Krasnoyarsk Territor'),
(	'RU','25',N'Primorye Territory'),
(	'RU','26',N'Stavropol Territory'),
(	'RU','27',N'Khabarovsk Territory'),
(	'RU','28',N'The Amur Area'),
(	'RU','29',N'The Arkhangelsk Area'),
(	'RU','30',N'The Astrakhan Area'),
(	'RU','31',N'The Belgorod Area'),
(	'RU','32',N'The Bryansk Area'),
(	'RU','33',N'The Vladimir Area'),
(	'RU','34',N'The Volgograd Area'),
(	'RU','35',N'The Vologda Area'),
(	'RU','36',N'The Voronezh Area'),
(	'RU','37',N'The Ivanovo Area'),
(	'RU','38',N'The Irkutsk Area'),
(	'RU','39',N'The Kaliningrad Area'),
(	'RU','40',N'The Kaluga Area'),
(	'RU','41',N'The Kamchatka Area'),
(	'RU','42',N'The Kemerovo Area'),
(	'RU','43',N'The Kirov Area'),
(	'RU','44',N'The Kostroma Area'),
(	'RU','45',N'The Kurgan Area'),
(	'RU','46',N'The Kursk Area'),
(	'RU','47',N'The Leningrad Area'),
(	'RU','48',N'The Lipetsk Area'),
(	'RU','49',N'The Magadan Area'),
(	'RU','50',N'The Moscow Area'),
(	'RU','51',N'The Murmansk Area'),
(	'RU','52',N'The Nizhniy Novgorod'),
(	'RU','53',N'The Novgorod Area'),
(	'RU','54',N'The Novosibirsk Area'),
(	'RU','55',N'The Omsk Area'),
(	'RU','56',N'The Orenburg Area'),
(	'RU','57',N'The Oryol Area'),
(	'RU','58',N'The Penza Area'),
(	'RU','59',N'The Perm Area'),
(	'RU','60',N'The Pskov Area'),
(	'RU','61',N'The Rostov Area'),
(	'RU','62',N'The Ryazan Area'),
(	'RU','63',N'The Samara Area'),
(	'RU','64',N'The Saratov Area'),
(	'RU','65',N'The Sakhalin Area'),
(	'RU','66',N'The Sverdlovsk Area'),
(	'RU','67',N'The Smolensk Area'),
(	'RU','68',N'The Tambov Area'),
(	'RU','69',N'The Tver Area'),
(	'RU','70',N'The Tomsk Area'),
(	'RU','71',N'The Tula Area'),
(	'RU','72',N'The Tyumen Area'),
(	'RU','73',N'The Ulyanovsk Area'),
(	'RU','74',N'The Chelyabinsk Area'),
(	'RU','75',N'The Chita Area'),
(	'RU','76',N'The Yaroslavl Area'),
(	'RU','77',N'c.Moscow'),
(	'RU','78',N'c.St-Peterburg'),
(	'RU','79',N'The Jewish Auton.are'),
(	'RU','80',N'Aginsk Buryat Aut.di'),
(	'RU','81',N'Komy Permjats.Aut.di'),
(	'RU','82',N'Korjacs Auton.distri'),
(	'RU','83',N'Nenekchky Auton.dist'),
(	'RU','84',N'The Taymir Auton.dis'),
(	'RU','85',N'Ust-Ordinsky Buryat'),
(	'RU','86',N'Chanti-Mansyjsky Aut'),
(	'RU','87',N'Chukotka Auton. dist'),
(	'RU','88',N'Evensky Auton.distri'),
(	'RU','89',N'Jamalo-Nenekchky Aut'),
(	'SE','001',N'Blekinge Län'),
(	'SE','002',N'Dalarnas Län'),
(	'SE','003',N'Gotlands Län'),
(	'SE','004',N'Gävleborgs Län'),
(	'SE','005',N'Hallands Län'),
(	'SE','006',N'Jämtlands Län'),
(	'SE','007',N'Jönköpings Län'),
(	'SE','008',N'Kalmar Län'),
(	'SE','009',N'Kronobergs Län'),
(	'SE','010',N'Norrbottens Län'),
(	'SE','011',N'Skåne Län'),
(	'SE','012',N'Stockholms Län'),
(	'SE','013',N'Södermanlands Län'),
(	'SE','014',N'Uppsala Län'),
(	'SE','015',N'Värmlands Län'),
(	'SE','016',N'Västerbottens Län'),
(	'SE','017',N'Västernorrlands Län'),
(	'SE','018',N'Västmanlands Län'),
(	'SE','019',N'Västra Götalands Län'),
(	'SE','020',N'Örebro Län'),
(	'SE','021',N'Östergötlands Län'),
(	'SG','SG',N'Singapore'),
(	'SI','01',N'Ajdovscina'),
(	'SI','02',N'Brezice'),
(	'SI','03',N'Celje'),
(	'SI','04',N'Cerknica'),
(	'SI','05',N'Crnomelj'),
(	'SI','06',N'Dravograd'),
(	'SI','07',N'Gornja Radgona'),
(	'SI','08',N'Grosuplje'),
(	'SI','09',N'Hrastnik Lasko'),
(	'SI','10',N'Idrija'),
(	'SI','11',N'Ilirska Bistrica'),
(	'SI','12',N'Izola'),
(	'SI','13',N'Jesenice'),
(	'SI','14',N'Kamnik'),
(	'SI','15',N'Kocevje'),
(	'SI','16',N'Koper'),
(	'SI','17',N'Kranj'),
(	'SI','18',N'Krsko'),
(	'SI','19',N'Lenart'),
(	'SI','20',N'Lendava'),
(	'SI','21',N'Litija'),
(	'SI','22',N'Ljubljana-Bezigrad'),
(	'SI','23',N'Ljubljana-Center'),
(	'SI','24',N'Ljubljana-Moste-Polj'),
(	'SI','25',N'Ljubljana-Siska'),
(	'SI','26',N'Ljubljana-Vic-Rudnik'),
(	'SI','27',N'Ljutomer'),
(	'SI','28',N'Logatec'),
(	'SI','29',N'Maribor'),
(	'SI','30',N'Metlika'),
(	'SI','31',N'Mozirje'),
(	'SI','32',N'Murska Sobota'),
(	'SI','33',N'Nova Gorica'),
(	'SI','34',N'Novo Mesto'),
(	'SI','35',N'Ormoz'),
(	'SI','36',N'Pesnica'),
(	'SI','37',N'Piran'),
(	'SI','38',N'Postojna'),
(	'SI','39',N'Ptuj'),
(	'SI','40',N'Radlje Ob Dravi'),
(	'SI','41',N'Radovljica'),
(	'SI','42',N'Ravne Na Koroskem'),
(	'SI','43',N'Ribnica'),
(	'SI','44',N'Ruse'),
(	'SI','45',N'Sentjur Pri Celju'),
(	'SI','46',N'Sevnica'),
(	'SI','47',N'Sezana'),
(	'SI','48',N'Skofja Loka'),
(	'SI','49',N'Slovenj Gradec'),
(	'SI','50',N'Slovenska Bistrica'),
(	'SI','51',N'Slovenske Konjice'),
(	'SI','52',N'Smarje Pri Jelsah'),
(	'SI','53',N'Tolmin'),
(	'SI','54',N'Trbovlje'),
(	'SI','55',N'Trebnje'),
(	'SI','56',N'Trzic'),
(	'SI','57',N'Velenje'),
(	'SI','58',N'Vrhnika'),
(	'SI','59',N'Zagorje Ob Savi'),
(	'SI','60',N'Zalec'),
(	'SK','01',N'Bratislava'),
(	'SK','02',N'Zapadoslovensky'),
(	'SK','03',N'Stredoslovensky'),
(	'SK','04',N'Vychodoslovensky'),
(	'TH','01',N'Amnat Charoen'),
(	'TH','02',N'Ang Thong'),
(	'TH','03',N'Buriram'),
(	'TH','04',N'Chachoengsao'),
(	'TH','05',N'Chai Nat'),
(	'TH','06',N'Chaiyaphum'),
(	'TH','07',N'Chanthaburi'),
(	'TH','08',N'Chiang Mai'),
(	'TH','09',N'Chiang Rai'),
(	'TH','10',N'Chon Buri'),
(	'TH','11',N'Chumphon'),
(	'TH','12',N'Kalasin'),
(	'TH','13',N'Kamphaeng Phet'),
(	'TH','14',N'Kanchanaburi'),
(	'TH','15',N'Khon Kaen'),
(	'TH','16',N'Krabi'),
(	'TH','17',N'Krung Thep'),
(	'TH','18',N'Mahanakhon'),
(	'TH','19',N'Lampang'),
(	'TH','20',N'Lamphun'),
(	'TH','21',N'Loei'),
(	'TH','22',N'Lop Buri'),
(	'TH','23',N'Mae Hong Son'),
(	'TH','24',N'Maha Sarakham'),
(	'TH','25',N'Mukdahan'),
(	'TH','26',N'Nakhon Nayok'),
(	'TH','27',N'Nakhon Pathom'),
(	'TH','28',N'Nakhon Phanom'),
(	'TH','29',N'Nakhon Ratchasima'),
(	'TH','30',N'Nakhon Sawan'),
(	'TH','31',N'Nakhon Si Thammarat'),
(	'TH','32',N'Nan'),
(	'TH','33',N'Narathiwat'),
(	'TH','34',N'Nong Bua Lamphu'),
(	'TH','35',N'Nong Khai'),
(	'TH','36',N'Nonthaburi'),
(	'TH','37',N'Pathum Thani'),
(	'TH','38',N'Pattani'),
(	'TH','39',N'Phangnga'),
(	'TH','40',N'Phatthalung'),
(	'TH','41',N'Phayao'),
(	'TH','42',N'Phetchabun'),
(	'TH','43',N'Phetchaburi'),
(	'TH','44',N'Phichit'),
(	'TH','45',N'Phitsanulok'),
(	'TH','46',N'Phra Nakhon Si Ayut.'),
(	'TH','47',N'Phrae'),
(	'TH','48',N'Phuket'),
(	'TH','49',N'Prachin Buri'),
(	'TR','01',N'Adana'),
(	'TR','02',N'Adiyaman'),
(	'TR','03',N'Afyon'),
(	'TR','04',N'Agri'),
(	'TR','05',N'Amasya'),
(	'TR','06',N'Ankara'),
(	'TR','07',N'Antalya'),
(	'TR','08',N'Artvin'),
(	'TR','09',N'Aydin'),
(	'TR','10',N'Balikesir'),
(	'TR','11',N'Bilecik'),
(	'TR','12',N'Bingöl'),
(	'TR','13',N'Bitlis'),
(	'TR','14',N'Bolu'),
(	'TR','15',N'Burdur'),
(	'TR','16',N'Bursa'),
(	'TR','17',N'Canakkale'),
(	'TR','18',N'Cankiri'),
(	'TR','19',N'Corum'),
(	'TR','20',N'Denizli'),
(	'TR','21',N'Diyarbakir'),
(	'TR','22',N'Edirne'),
(	'TR','23',N'Elazig'),
(	'TR','24',N'Erzincan'),
(	'TR','25',N'Erzurum'),
(	'TR','26',N'Eskisehir'),
(	'TR','27',N'Gaziantep'),
(	'TR','28',N'Giresun'),
(	'TR','29',N'Gümüshane'),
(	'TR','30',N'Hakkari'),
(	'TR','31',N'Hatay'),
(	'TR','32',N'Isparta'),
(	'TR','33',N'Icel'),
(	'TR','34',N'Istanbul'),
(	'TR','35',N'Izmir'),
(	'TR','36',N'Kars'),
(	'TR','37',N'Kastamonu'),
(	'TR','38',N'Kayseri'),
(	'TR','39',N'Kirklareli'),
(	'TR','40',N'Kirshehir'),
(	'TR','41',N'Kocaeli'),
(	'TR','42',N'Konya'),
(	'TR','43',N'Kütahya'),
(	'TR','44',N'Malatya'),
(	'TR','45',N'Manisa'),
(	'TR','46',N'K.Marash'),
(	'TR','47',N'Mardin'),
(	'TR','48',N'Mugla'),
(	'TR','49',N'Mush'),
(	'TR','50',N'Nevshehir'),
(	'TR','51',N'Nigde'),
(	'TR','52',N'Ordu'),
(	'TR','53',N'Rize'),
(	'TR','54',N'Sakarya'),
(	'TR','55',N'Samsun'),
(	'TR','56',N'Siirt'),
(	'TR','57',N'Sinop'),
(	'TR','58',N'Sivas'),
(	'TR','59',N'Tekirdag'),
(	'TR','60',N'Tokat'),
(	'TR','61',N'Trabzon'),
(	'TR','62',N'Tunceli'),
(	'TR','63',N'Shanliurfa'),
(	'TR','64',N'Ushak'),
(	'TR','65',N'Van'),
(	'TR','66',N'Yozgat'),
(	'TR','67',N'Zonguldak'),
(	'TR','68',N'Aksaray'),
(	'TR','69',N'Bayburt'),
(	'TR','70',N'Karaman'),
(	'TR','71',N'Kirikkale'),
(	'TR','72',N'Batman'),
(	'TR','73',N'Shirnak'),
(	'TR','74',N'Bartin'),
(	'TR','75',N'Ardahan'),
(	'TR','76',N'Igdir'),
(	'TR','77',N'Yalova'),
(	'TW','FJN',N'Fu-chien'),
(	'TW','KSH',N'Kao-hsiung'),
(	'TW','TPE',N'T´ai-pei'),
(	'TW','TWN',N'Taiwan'),
(	'UA','CHG',N'Chernigivs''ka'),
(	'UA','CHR',N'Cherkas''ka'),
(	'UA','CHV',N'Chernovits''ka'),
(	'UA','DNP',N'Dnipropetrovs''ka'),
(	'UA','DON',N'Donets''ka'),
(	'UA','HAR',N'Harkivs''ka'),
(	'UA','HML',N'Hmel''nits''ka'),
(	'UA','HRS',N'Hersons''ka'),
(	'UA','IVF',N'Ivano-Frankivs''ka'),
(	'UA','KIE',N'Kievs''ka'),
(	'UA','KIR',N'Kirovograds''ka'),
(	'UA','KRM',N'Respublika Krim'),
(	'UA','LUG',N'Lugans''ka'),
(	'UA','L''V',N'L''vivsbka'),
(	'UA','M_K',N'm.Kiev'),
(	'UA','M_S',N'm.Sevastopil'''),
(	'UA','MIK',N'Mikolaivs''ka'),
(	'UA','ODS',N'Odes''ka'),
(	'UA','POL',N'Poltavs''ka'),
(	'UA','RIV',N'Rivnens''ka'),
(	'UA','SUM',N'Sums''ka'),
(	'UA','TER',N'Ternopil''s''ka'),
(	'UA','VIN',N'Vinnits''ka'),
(	'UA','VOL',N'Volins''ka'),
(	'UA','ZAK',N'Zakarpats''ka'),
(	'UA','ZAP',N'Zaporiz''ka'),
(	'UA','ZHI',N'Zhitomirs''ka'),
(	'US','AA',N'Armed Forces America'),
(	'US','AE',N'Armed Forces Europe'),
(	'US','AK',N'Alaska'),
(	'US','AL',N'Alabama'),
(	'US','AP',N'Armed Forces Pacific'),
(	'US','AR',N'Arkansas'),
(	'US','AS',N'American Samoa'),
(	'US','AZ',N'Arizona'),
(	'US','CA',N'California'),
(	'US','CO',N'Colorado'),
(	'US','CT',N'Connecticut'),
(	'US','DC',N'District of Columbia'),
(	'US','DE',N'Delaware'),
(	'US','FL',N'Florida'),
(	'US','GA',N'Georgia'),
(	'US','GU',N'Guam'),
(	'US','HI',N'Hawaii'),
(	'US','IA',N'Iowa'),
(	'US','ID',N'Idaho'),
(	'US','IL',N'Illinois'),
(	'US','IN',N'Indiana'),
(	'US','KS',N'Kansas'),
(	'US','KY',N'Kentucky'),
(	'US','LA',N'Louisiana'),
(	'US','MA',N'Massachusetts'),
(	'US','MD',N'Maryland'),
(	'US','ME',N'Maine'),
(	'US','MI',N'Michigan'),
(	'US','MN',N'Minnesota'),
(	'US','MO',N'Missouri'),
(	'US','MP',N'Northern Mariana Isl'),
(	'US','MS',N'Mississippi'),
(	'US','MT',N'Montana'),
(	'US','NC',N'North Carolina'),
(	'US','ND',N'North Dakota'),
(	'US','NE',N'Nebraska'),
(	'US','NH',N'New Hampshire'),
(	'US','NJ',N'New Jersey'),
(	'US','NM',N'New Mexico'),
(	'US','NP',N'No Plate'),
(	'US','NV',N'Nevada'),
(	'US','NY',N'New York'),
(	'US','OH',N'Ohio'),
(	'US','OK',N'Oklahoma'),
(	'US','OR',N'Oregon'),
(	'US','PA',N'Pennsylvania'),
(	'US','PP',N'Paper Plate'),
(	'US','PR',N'Puerto Rico'),
(	'US','RI',N'Rhode Island'),
(	'US','SC',N'South Carolina'),
(	'US','SD',N'South Dakota'),
(	'US','TN',N'Tennessee'),
(	'US','TX',N'Texas'),
(	'US','UT',N'Utah'),
(	'US','VA',N'Virginia'),
(	'US','VI',N'Virgin Islands'),
(	'US','VT',N'Vermont'),
(	'US','WA',N'Washington'),
(	'US','WI',N'Wisconsin'),
(	'US','WV',N'West Virginia'),
(	'US','WY',N'Wyoming'),
(	'VE','AMA',N'Amazon'),
(	'VE','ANZ',N'Anzoategui'),
(	'VE','APU',N'Apure'),
(	'VE','ARA',N'Aragua'),
(	'VE','BAR',N'Barinas'),
(	'VE','BOL',N'Bolivar'),
(	'VE','CAR',N'Carabobo'),
(	'VE','COJ',N'Cojedes'),
(	'VE','DA',N'Delta Amacuro'),
(	'VE','DF',N'Distrito Federal'),
(	'VE','FAL',N'Falcon'),
(	'VE','GUA',N'Guarico'),
(	'VE','LAR',N'Lara'),
(	'VE','MER',N'Merida'),
(	'VE','MIR',N'Miranda'),
(	'VE','MON',N'Monagas'),
(	'VE','NE',N'Nueva Esparta'),
(	'VE','POR',N'Portuguesa'),
(	'VE','SUC',N'Sucre'),
(	'VE','TAC',N'Tachira'),
(	'VE','TRU',N'Trujillo'),
(	'VE','VAR',N'Vargas'),
(	'VE','YAR',N'Yaracuy'),
(	'VE','ZUL',N'Zulia'),
(	'ZA','EC',N'Eastern Cape'),
(	'ZA','FS',N'Freestate'),
(	'ZA','GP',N'Gauteng'),
(	'ZA','KZN',N'Kwazulu/Natal'),
(	'ZA','MP',N'Mpumalanga'),
(	'ZA','NC',N'Northern Cape'),
(	'ZA','NP',N'Northern Province'),
(	'ZA','NW',N'North-West'),
(	'ZA','WC',N'Western Cape');
INSERT INTO #CountryState ([CountryCode], [StateCode], [StateName])
VALUES 
(	'US','UM',N'United States Minor Outlying Islands'),
(	'US','PW',N'Palau'),
(	'US','FM',N'Federated States of Micronesia'),
(	'US','MH',N'Marshall Islands');


MERGE [Lookup].[CountryState] AS Tgt
USING #CountryState AS Src
  ON Tgt.[CountryCode] = Src.[CountryCode]
 AND Tgt.[StateCode] = Src.[StateCode]
WHEN MATCHED AND EXISTS (
  SELECT Src.[StateName]
  EXCEPT 
  SELECT Tgt.[StateName]
) THEN 
  UPDATE SET
        Tgt.[StateName] = Src.[StateName]
  WHEN NOT MATCHED BY TARGET THEN
    INSERT (
	  [SystemFromDate],
	  [SystemtoDate],
	  [CountryCode],
      [StateCode],
	  [StateName]
	)
	VALUES (
	  '1753-01-01',
	  '9999-12-31 23:59:59.9999999',
	  [CountryCode],
      [StateCode],
	  [StateName]
	);
GO
SELECT * FROM [Lookup].[CountryState];
GO

/* End of File ********************************************************************************************************************/