apiVersion: apps/v1
kind: Deployment
metadata:
  name: schemaregistry  
  namespace: "igbi-kafka-connect"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schemaregistry
  template:
    metadata:
      labels:
        app: schemaregistry
    spec:
      containers:
      - name: schemaregistry
        image: artifactory.tools1-az1.digi.is/epea-docker-pull/confluentinc/cp-schema-registry:7.5.0
        ports:
        - containerPort: 8081
        env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: "schemaregistry"
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: "broker:29092"
        - name: SCHEMA_REGISTRY_LISTENERS
          value: "http://0.0.0.0:8081"
        - name: SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL
          value: "BACKWARD"
        - name: SCHEMA_REGISTRY_MODE
          value: "READWRITE"
---
apiVersion: v1
kind: Service
metadata:
  name: schemaregistry
  namespace: "igbi-kafka-connect"
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: schemaregistry          