apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: "igbi-kafka-connect"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: artifactory.tools1-az1.digi.is/epea-docker-ms/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_AGENT_ENABLED
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "sql@dm1n"
        volumeMounts:
        - name: sqlserver
          mountPath: /var/opt/mssql
      volumes:
      - name: sqlserver
        persistentVolumeClaim:
          claimName: sqlserver-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-data
  namespace: "igbi-kafka-connect"
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
---        
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: "igbi-kafka-connect"
spec:
  ports:
  - port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    app: sqlserver
  type: LoadBalancer      